apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: deployment/manifests/if-demo
    repoURL: https://github.com/kimberlyeder/devops-exercise
    targetRevision: 
    helm:
      releaseName: hello-app
  sources: []
  project: hello-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
