replicaCount: 1

image:
  repository: kimberlyeder/hello-app
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  hosts:
    - host: hello.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: []

env:
  APP_NAME: "hello-app"
